import { inject, LangiumSharedCoreServices, type Module } from "langium";
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from "langium/lsp";
import {
  createTypirLangiumServicesWithAdditionalServices,
  initializeLangiumTypirServices
} from "typir-langium";
import { ELangAddedServices, ELangServices } from "./ELangServices.type.js";
import { ELangHoverProvider } from "./e-lang-hover-provider.js";
import { ELangScopeComputation } from "./e-lang-scope-computation.js";
import { ELangScopeProvider } from "./e-lang-scope-provider.js";
import { ELangValidator } from "./e-lang-validator.js";
import { reflection } from "./generated/ast.js";
import {
  ELangGeneratedModule,
  ELangGeneratedSharedModule,
} from "./generated/module.js";
import { ELangAdditionalTypirServices } from "./type-system/ELangAdditionalTypirServices.type.js";
import { ELangSpecifics } from "./type-system/ELangSpecifics.interface.js";
import { ELangTypeSystem } from "./type-system/ELangTypeSystem.class.js";
import { dimensionFactory } from "./type-system/custom-types/dimension/dimensionFactory.js";
import { modelFactory } from "./type-system/custom-types/model/modelFactory.js";
import { unitFactory } from "./type-system/custom-types/unit/unitFactory.js";
import { ELangNameProvider } from "./e-lang-name-provider.js";


export function createELangModule(shared: LangiumSharedCoreServices): Module<ELangServices, PartialLangiumServices & ELangAddedServices> {
  return {
    validation: {
    ELangValidator: () => new ELangValidator(),
  },
  lsp: {
    HoverProvider: (services) => new ELangHoverProvider(services),
  },
  references: {
    ScopeProvider: (services) => new ELangScopeProvider(services),
    ScopeComputation: (services) => new ELangScopeComputation(services),
    NameProvider: () => new ELangNameProvider(),
  },
  typir: (services) =>
    createTypirLangiumServicesWithAdditionalServices<
      ELangSpecifics,
      ELangAdditionalTypirServices
    >(services.shared, reflection, new ELangTypeSystem(), {
      factory: {
        Dimension: dimensionFactory,
        Unit: unitFactory,
        Model: modelFactory,
      },
    }),
  }
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createELangServices(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  ELang: ELangServices;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    ELangGeneratedSharedModule
  );

  const ELang = inject(
    createDefaultModule({ shared }),
    ELangGeneratedModule,
    createELangModule(shared)
  );

  shared.ServiceRegistry.register(ELang);

  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({});
  }

  initializeLangiumTypirServices(ELang, ELang.typir);

  return { shared, ELang };
}
